services:
  techdraw-app:
    build: .
    container_name: techdraw-translator
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ./:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: python -m app.main

  techdraw-tests:
    build: .
    container_name: techdraw-tests
    volumes:
      - ./:/app
    command: pytest -q
